version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2185:2181" # Ánh xạ cổng từ 2185 sang 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Vẫn giữ cổng 2181 cho Zookeeper

  producer-app:
    build:
      context: ./producer
    environment:
      KAFKA_BROKER: kafka:9093
    depends_on:
      - kafka

  consumer-app:
    build:
      context: ./consumer
    environment:
      KAFKA_BROKER: kafka:9093
    depends_on:
      - kafka
